---
title: "Untitled"
author: "roger"
date: "August 31, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(EUFLOW)
options(stringsAsFactors = FALSE)

```

The contents of this package are:
```{r}
search() 
ls(pos=2)
```

We now test the package using test.R contents.
```{r}

RNASEQDATA<-read.csv(file="../data/RNASEQDATA.csv",header=TRUE)
RPPADATA<-read.csv(file="../data/RPPADATA.original.csv",header=TRUE)
EvaluationExperimentSet<-RNASEQDATA
#EvaluationExperimentSet<-rbind(RNASEQDATA,RANDOMSET)
ReferenceSet<-RPPADATA
Workflow.Data<-WorkflowEvaluationData(EvaluationExperimentSet,ReferenceSet)
Merged.options<-merge_tag_options(Workflow.Data)
Model.quality.object<-Model.quality.list(Merged.options)
Model.Quality<-EUFLOW:::Workflow.Criterion(Model.quality.object)
Posterior.dataframe<-Workflow.posteriorestimate(Model.quality.object,Model.Quality)
Workflow.Evaluation.table(Posterior.dataframe)
Workflow.Evaluation.table(Posterior.dataframe,deltaPlus = 2)
Workflow.Evaluation.table(Posterior.dataframe,Utp=3)
Workflow.Evaluation.table(Posterior.dataframe,Utp=1)
```
